TEST_TOOL_ROOTS :=
TEST_ROOTS :=
TOOL_ROOTS := exectrace
SA_TOOL_ROOTS :=
APP_ROOTS :=
OBJECT_ROOTS :=
DLL_ROOTS :=
LIB_ROOTS :=
SANITY_SUBSET :=

TOOL_CXXFLAGS += -O0
TOOL_LPATH +=
TOOL_LIBS +=
TOOL_OBJS = \
    $(OBJDIR)exectrace$(OBJ_SUFFIX)

TEST_DIR := ../test_libressl
TEST_OBJ := $(TEST_DIR)/test
TEST_INPUT_DIR := $(TEST_DIR)/input
TRACE_DIR := $(TEST_DIR)/traces

.PHONY: test
test: $(OBJDIR)exectrace$(PINTOOL_SUFFIX)
	rm -rf $(TRACE_DIR)
	mkdir -p $(TRACE_DIR)
#	$(CXX) -ggdb3 -o $(TEST_OBJ) $(TEST_CPP)
	@$(foreach input, $(wildcard $(TEST_INPUT_DIR)/*), \
	echo "Running $(input)"; $(PIN) -t $(OBJDIR)exectrace$(PINTOOL_SUFFIX) \
	-o $(TRACE_DIR)/$(basename $(notdir $(input))).trace \
	-- $(TEST_OBJ) $(input); )

SORT_CPP := qsort.c
SORT_OBJ := ./qsort
SORT_INPUT := qsort_test.txt

.PHONY: qsort
qsort: $(OBJDIR)exectrace$(PINTOOL_SUFFIX)
	$(CXX) -o $(SORT_OBJ) $(SORT_CPP)
	$(PIN) -t $(OBJDIR)exectrace$(PINTOOL_SUFFIX) -- $(SORT_OBJ) $(SORT_INPUT) -o

$(OBJDIR)exectrace$(PINTOOL_SUFFIX): $(TOOL_OBJS)
	$(LINKER) $(TOOL_LDFLAGS) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS)
